# Generated by Django 2.1.1 on 2019-03-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_post_text', models.TextField(max_length='5000')),
                ('wiki_post_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/')),
            ],
        ),
    ]
