# Generated by Django 2.1.1 on 2019-03-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_wiki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipost',
            name='wiki_post_image',
            field=models.ImageField(blank=True, null=True, upload_to='{{MEDIA_URL}}images/%Y/%m/%D/'),
        ),
    ]
