# Generated by Django 2.1.1 on 2019-03-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_wiki_app', '0002_auto_20190308_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipost',
            name='wiki_post_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='wiki_post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='wiki_post_text',
            field=models.TextField(max_length=5000),
        ),
    ]
