# Generated by Django 2.1.1 on 2019-03-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_wiki_app', '0003_auto_20190308_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipost',
            name='wiki_post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%D/'),
        ),
    ]
