# Generated by Django 2.1.1 on 2019-03-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_wiki_app', '0005_auto_20190309_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPostLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_post_lineitem_text', models.TextField(max_length=5000)),
                ('wiki_post_lineitem_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
            ],
        ),
    ]
