# Generated by Django 2.1.1 on 2019-03-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_wiki_app', '0007_auto_20190309_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipostlineitem',
            name='wiki_post_lineitem_text',
            field=models.TextField(max_length=1000),
        ),
    ]
